languageCode = "en"
title = "Wanderings | A blog"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
#disqusShortname = "shortname"
#googleAnalytics = "trackingcode"

[taxonomies]
tag = "go"
#category = "categories"

[params]
description = "Tech Blog"
keywords = ["technology","blog"]
author = "hacktohell"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/hacktohell"
fa_icon = "fa-github"

#[[params.social]]
#url = "https://gitlab.com/mgjohansen"
#fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/hacktohell"
fa_icon = "fa-twitter"

#[[params.social]]
#url = "https://linkedin.com/in/mgjohansen"
#fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

#[[params.socialshare]]
#url = "https://linkedin.com/in/mgjohansen"
#fa_icon = "fa-linkedin-square"
